### ISSUE TITLE
Question: Fill background up to the line

### ISSUE THREAD

**Issue by OnurGumus** [compostjs/compost#4]
This is more like a question but I am curious how to achieve the following : 
Suppose we have the following
![image](https://user-images.githubusercontent.com/4114592/84784149-469b1c80-afea-11ea-96f1-a49b9e8272ac.png)

I would like the colored areas limited by the line and would like to keep the area above the line as white. Is this doable?

**Comment by tpetricek** [comment]
Good question!

The background shapes do not have to be rectangles - the `c.shape` primitive will fill any polygon you give it - so the way to do this is to generate the points of this background so that it is flat at the bottom, but aligned with the data points at the top.

I added this as a demo: https://compostjs.github.io/compost/demos.html#xchg-under


![image](https://user-images.githubusercontent.com/485413/84825173-f2f3f780-b018-11ea-80c6-1c835e40d78c.png)
